import type { WorkspaceManifest } from "@/lib/daemon/client";

// First-paint projection generated from webapp.daemon.manifest_service.build_manifest()
// on 2026-06-25. It keeps the packaged Tauri shell/sidebar deterministic while
// the sidecar reaches readiness; the live daemon manifest replaces it as soon
// as /api/workspace/manifest answers.
export const FALLBACK_WORKSPACE_MANIFEST = {
  topActions: [
    { id: "new", label: "New", enabled: true, shortcut: "Ctrl+N" },
    { id: "open", label: "Open", enabled: true, shortcut: "CmdOrCtrl+O" },
    { id: "now", label: "Here and Now", enabled: true, shortcut: "Ctrl+R" },
  ],
  groups: [
    {
      id: "charts",
      label: "Charts",
      collapsed: false,
      actions: [
        { id: "directions", label: "Primary Directions", enabled: true, shortcut: "D" },
        { id: "secondary-progression", label: "Secondary Progression", enabled: true, shortcut: "S" },
        { id: "tertiary-progression", label: "Tertiary Progression", enabled: true },
        { id: "minor-progression", label: "Minor Progression", enabled: true },
        { id: "profections", label: "Profections", enabled: true, shortcut: "P" },
        { id: "harmonic", label: "Harmonic chart", enabled: true },
        { id: "solar-revolution", label: "Solar Revolution", enabled: true, shortcut: "R" },
        { id: "lunar-revolution", label: "Lunar Revolution", enabled: true, shortcut: "L" },
        { id: "transits", label: "Transits", enabled: true, shortcut: "T" },
        { id: "solar-arc", label: "Solar Arc", enabled: true },
        { id: "synastry", label: "Synastry", enabled: true, shortcut: "Ctrl+Y" },
        { id: "astrolabe", label: "Astrolabe", enabled: true },
        { id: "astrocartography", label: "Astrocartography", enabled: true },
        {
          id: "planetary-return",
          label: "Planetary Return",
          enabled: true,
          bodies: [
            { planetType: 2, label: "Mercury" },
            { planetType: 3, label: "Venus" },
            { planetType: 4, label: "Mars" },
            { planetType: 5, label: "Jupiter" },
            { planetType: 6, label: "Saturn" },
            { planetType: 7, label: "Uranus" },
            { planetType: 8, label: "Neptune" },
            { planetType: 9, label: "Pluto" },
          ],
        },
      ],
    },
    {
      id: "tables",
      label: "Tables",
      collapsed: false,
      actions: [
        { id: "table:positions", label: "Positions", enabled: true, shortcut: "F1" },
        { id: "table:lunar_mansions", label: "Lunar Mansions", enabled: true },
        { id: "table:eclipses", label: "Eclipses", enabled: true, shortcut: "E" },
        { id: "table:antiscia", label: "Antiscia", enabled: true, shortcut: "F7" },
        { id: "ephemeris", label: "Graphic Ephemeris", enabled: true },
        { id: "table:synodic_cycles", label: "Synodic Cycles", enabled: true, shortcut: "Q" },
        { id: "table:dodecatemoria", label: "Dodecatemoria", enabled: true, shortcut: "Ctrl+F10" },
        { id: "table:aspects", label: "Aspects", enabled: true, shortcut: "F8" },
        { id: "table:aspect_list", label: "Aspect List", enabled: true, shortcut: "X" },
        { id: "table:midpoints", label: "Midpoints", enabled: true, shortcut: "F9" },
        { id: "table:asteroids", label: "Asteroids", enabled: true },
        { id: "table:mundane_positions", label: "Mundane Positions", enabled: true, shortcut: "F6" },
        { id: "table:zodpars", label: "Zod. Pars", enabled: true, shortcut: "F12" },
        { id: "table:arabic_parts", label: "Arabic Parts", enabled: true, shortcut: "Ctrl+F3" },
        { id: "table:planetary_hours", label: "Planetary Hours", enabled: true, shortcut: "Ctrl+F5" },
        { id: "table:almuten_zodiacal", label: "Almuten Zodiacal", enabled: true, shortcut: "F2" },
        { id: "table:almuten_chart", label: "Almuten Chart", enabled: true, shortcut: "F3" },
        { id: "table:speeds", label: "Planetary Speeds", enabled: true, shortcut: "F11" },
        { id: "table:strip", label: "Strip", enabled: true, shortcut: "Ctrl+F4" },
        { id: "table:profections_table", label: "Profections", enabled: true, shortcut: "Ctrl+F7" },
        { id: "table:rise_set", label: "Rise / Set", enabled: true, shortcut: "F10" },
        { id: "table:angle_at_birth", label: "Angle at Birth", enabled: true, shortcut: "Ctrl+F11" },
        { id: "table:phasis", label: "Phasis", enabled: true, shortcut: "Ctrl+2" },
        { id: "table:paranatellonta", label: "Paranatellonta", enabled: true, shortcut: "Ctrl+3" },
        { id: "table:fixed_stars", label: "Fixed Stars", enabled: true, shortcut: "Ctrl+F1" },
        { id: "table:fixed_stars_aspects", label: "Fixed Stars Aspects", enabled: true, shortcut: "Ctrl+F2" },
        { id: "table:fixed_stars_parallels", label: "Fixed Stars Parallels", enabled: true, shortcut: "Ctrl+8" },
        { id: "table:misc", label: "Miscellaneous", enabled: true, shortcut: "F5" },
      ],
    },
    {
      id: "time-lords",
      label: "Time Lords",
      collapsed: false,
      actions: [
        { id: "table:vimshottari", label: "Vimshottari Dasha", enabled: true },
        { id: "directions:circumambulation", label: "Circumambulations", enabled: true, shortcut: "C" },
        { id: "table:zodiacal_releasing", label: "Zodiacal Releasing", enabled: true, shortcut: "Z" },
        { id: "table:decennials", label: "Decennials", enabled: true, shortcut: "Ctrl+7" },
        { id: "table:firdaria", label: "Firdaria", enabled: true, shortcut: "Ctrl+F9" },
      ],
    },
    {
      id: "research",
      label: "Research",
      collapsed: false,
      actions: [
        { id: "table:triplicity_directions", label: "Triplicity Directions", enabled: true },
        { id: "solar-average", label: "Average Returns", enabled: true },
        { id: "transit-search", label: "Search", enabled: true, shortcut: "Ctrl+F" },
      ],
    },
  ],
  shortcuts: [
    { keys: "?", label: "Toggle keyboard shortcuts", group: "WORKSPACE", labelKey: "help.shortcut.showKeyHints", bound: true },
    { keys: "I", label: "Inspector", group: "WORKSPACE", commandId: "toggle-inspector", bound: true },
    { keys: "⌘ E", label: "Data", group: "WORKSPACE", commandId: "menu.data", bound: true },
    { keys: "⌘ ⇧ 0", label: "", group: "", commandId: "toggle-presentation-cursor", hidden: true, bound: true },
    { keys: "⌘ W", label: "Close window", group: "WORKSPACE", commandId: "workspace.close-active", bound: true },
    { keys: "⌘ F", label: "Search", group: "WORKSPACE", commandId: "transit-search", bound: true },
    { keys: "⌘ Y", label: "Synastry", group: "WORKSPACE", commandId: "synastry", bound: true },
    { keys: "⌘ ⌥ A", label: "Ascensional transits", group: "WORKSPACE", commandId: "ascensional-transits", bound: true },
    { keys: "⌘ N", label: "New", group: "WORKSPACE", labelKey: "sidebar.action.new", bound: true },
    { keys: "⌘ R", label: "Here and Now", group: "WORKSPACE", labelKey: "sidebar.action.now", bound: true },
    { keys: "⌘ O", label: "Open Horoscope...", group: "WORKSPACE", labelKey: "sidebar.action.open", bound: true },
    { keys: "⌘ S", label: "Save Horoscope", group: "WORKSPACE", labelKey: "home.save", bound: true },
    { keys: "⌘ ⇧ S", label: "Save As...", group: "WORKSPACE", labelKey: "nativeMenu.saveAs", bound: true },
    { keys: "⌘ ⇧ A", label: "Appearance", group: "WORKSPACE", labelKey: "appearance.title", bound: true },
    { keys: "⌘ ⇧ E", label: "Chart Style Lab", group: "WORKSPACE", labelKey: "styleLab.title", commandId: "open-style-lab", bound: true },
    { keys: "⌘ G", label: "Cycle secondary view", group: "WORKSPACE", labelKey: "nativeMenu.cycleSecondaryView", bound: true },
    { keys: "⌘ B", label: "Toggle sidebar", group: "WORKSPACE", labelKey: "toolbar.toggleSidebar", bound: true },
    { keys: "T", label: "Transits", group: "CHART MODES", commandId: "transits", bound: true },
    { keys: "R", label: "Solar Revolution", group: "CHART MODES", commandId: "solar-revolution", bound: true },
    { keys: "L", label: "Lunar Revolution", group: "CHART MODES", commandId: "lunar-revolution", bound: true },
    { keys: "S", label: "Secondary Progression", group: "CHART MODES", commandId: "secondary-progression", bound: true },
    { keys: "A", label: "Aspects", group: "CHART MODES", commandId: "toggle-aspects", bound: true },
    { keys: "M", label: "Minor aspects", group: "CHART MODES", commandId: "toggle-minor-aspects", bound: true },
    { keys: "P", label: "Profections", group: "CHART MODES", commandId: "profections", bound: true },
    { keys: "D", label: "Primary Directions", group: "CHART MODES", commandId: "directions", bound: true },
    { keys: "C", label: "Circumambulations", group: "CHART MODES", commandId: "directions:circumambulation", bound: true },
    { keys: "E", label: "Eclipses", group: "CHART MODES", commandId: "table:eclipses", bound: true },
    { keys: "Z", label: "Zodiacal Releasing", group: "CHART MODES", commandId: "table:zodiacal_releasing", bound: true },
    { keys: "Q", label: "Synodic Cycles", group: "CHART MODES", commandId: "table:synodic_cycles", bound: true },
    { keys: "X", label: "Aspect List", group: "CHART MODES", commandId: "table:aspect_list", bound: true },
    { keys: "H", label: "Toggle Houses", group: "CHART MODES", commandId: "toggle-houses", bound: true },
    { keys: "← / →", label: "day in transits / here-and-now charts", group: "TIME STEP", labelKey: "help.shortcut.contextualStep", bound: true },
    { keys: "⇧ + ← / →", label: "step hour", group: "TIME STEP", labelKey: "help.shortcut.finerStep", bound: true },
    { keys: "⌥ + ← / →", label: "step minute", group: "TIME STEP", labelKey: "help.shortcut.finestStep", bound: true },
    { keys: "↑ / ↓", label: "step a week", group: "TIME STEP", labelKey: "help.shortcut.weekOrListStep", bound: true },
    { keys: "⇧ + ↑ / ↓", label: "step to next lunar phase quarter", group: "TIME STEP", labelKey: "help.shortcut.lunarQuarter", bound: true },
    { keys: "Space", label: "Reset to initial chart", group: "TIME STEP", labelKey: "help.shortcut.resetInitialChart", bound: true },
    { keys: "Tab", label: "compare (derived charts only)", group: "VIEW", labelKey: "help.shortcut.toggleComparison", bound: true },
    { keys: "Esc", label: "close panel / overlay", group: "VIEW", labelKey: "help.shortcut.closePanel", bound: true },
    { keys: "⇧ ⇧", label: "open spotlight (double-tap shift)", group: "VIEW", labelKey: "help.shortcut.openSpotlight", bound: true },
    { keys: "0–9", label: "open spotlight (enter first digit)", group: "VIEW", labelKey: "help.shortcut.openSpotlightSeeded", bound: true },
  ],
} satisfies WorkspaceManifest;
