"""GENERATED (from label_i18n) — native Options submenu English label -> frontend catalog key.
Regenerate if the Options submenu labels change; the French lives in the frontend
catalog (optmenu.*), not here. Consumed by label_i18n.attach_label_keys."""

OPTIONS_MENU_KEYS = {
    'Node calculation': 'optmenu.nodeCalculation',
    'Ayanamsha': 'optmenu.ayanamsha',
    'House system': 'optmenu.houseSystem',
    'House System': 'optmenu.houseSystem2',
    'Chart layers': 'optmenu.chartLayers',
    'Aspects': 'optmenu.aspects',
    'Outer ring and signals': 'optmenu.outerRingAndSignals',
    'Planets and points': 'optmenu.planetsAndPoints',
    'Header and layout': 'optmenu.headerAndLayout',
    'Progressions and returns': 'optmenu.progressionsAndReturns',
    'Time lords and alerts': 'optmenu.timeLordsAndAlerts',
    'Other options': 'optmenu.otherOptions',
    'Theme presets': 'quickopt.themePresets',
    'Follow OS theme': 'quickopt.followOsTheme',
    'Mean Node': 'optmenu.meanNode',
    'True Node': 'optmenu.trueNode',
    'Moyens': 'optmenu.moyens',
    'Vrais': 'optmenu.vrais',
    'Galactic Center at 0° Sagittarius': 'optmenu.galacticCenterAt0Sagittarius',
    'Galactic Center (Gil Brand)': 'optmenu.galacticCenterGilBrand',
    'Dhruva/Galactic Center (Wilhelm)': 'optmenu.dhruvaWilhelm',
    'Aldebaran at 15° Taurus': 'optmenu.aldebaranAt15Taurus',
    'Aldebaran 15 Taureau': 'optmenu.aldebaran15Taureau',
    'Centre Galactique at 0 Sag.': 'optmenu.centreGalactiqueAt0Sag',
    'Babylonian, Kugler I': 'optmenu.babylonianKuglerI',
    'Babylonian, Kugler II': 'optmenu.babylonianKuglerIi',
    'Babylonian, Kugler III': 'optmenu.babylonianKuglerIii',
    'Babylonian, Huber': 'optmenu.babylonianHuber',
    'Babylonian, Mercier': 'optmenu.babylonianMercier',
    'Sassanian': 'optmenu.sassanian',
    'True Chitra': 'optmenu.trueChitra',
    'Equal': 'optmenu.equal',
    'Whole Sign': 'optmenu.wholeSign',
    'Axial Rotation': 'optmenu.axialRotation',
    'Axial': 'optmenu.axial',
    'True Ascendant': 'optmenu.trueAscendant',
    'Horizontal': 'optmenu.horizontal',
    'Horizon': 'optmenu.horizon',
    'Polich-Page (Topocentric)': 'optmenu.polichpageTopocentric',
    'Porphyry': 'optmenu.porphyry',
    'None': 'optmenu.none',
    'Houses': 'optmenu.houses',
    'House system label': 'optmenu.houseSystemLabel',
    'Nodes': 'optmenu.nodes',
    'Fortuna': 'optmenu.fortuna',
    'Prenatal Syzygy': 'optmenu.prenatalSyzygy',
    'In tables': 'optmenu.inTables',
    'Terms': 'optmenu.terms',
    'Decans': 'optmenu.decans',
    'Topocentric Moon': 'optmenu.topocentricMoon',
    'Morin antiscia': 'optmenu.morinAntiscia',
    'Pluto': 'optmenu.pluto',
    'With symbols': 'optmenu.withSymbols',
    'Traditional only': 'optmenu.traditionalOnly',
    'Aspects to Vertex': 'optmenu.aspectsToVertex',
    'Aspects to Nodes': 'optmenu.aspectsToNodes',
    'Aspects to Fortuna': 'optmenu.aspectsToFortuna',
    'Outer-ring Fortuna label': 'optmenu.outerringFortunaLabel',
    'Conjunction': 'optmenu.conjunction',
    'Semisextile': 'optmenu.semisextile',
    'Semisquare': 'optmenu.semisquare',
    'Sextile': 'optmenu.sextile',
    'Quintile': 'optmenu.quintile',
    'Square': 'optmenu.square',
    'Trine': 'optmenu.trine',
    'Sesquisquare': 'optmenu.sesquisquare',
    'Biquintile': 'optmenu.biquintile',
    'Quinqunx': 'optmenu.quinqunx',
    'Opposition': 'optmenu.opposition',
    'Septile': 'optmenu.septile',
    'Exclusive on click': 'optmenu.exclusiveOnClick',
    'Exclusive click: show minor': 'optmenu.exclusiveClickShowMinor',
    'Exclusive click: traditional': 'optmenu.exclusiveClickTraditional',
    'Orb as line thickness': 'optmenu.orbAsLineThickness',
    'Planets in hover flag': 'optmenu.planetsInHoverFlag',
    'Fixed Stars': 'optmenu.fixedStars',
    'Fixed stars': 'optmenu.fixedStars2',
    'Etoiles Fixes': 'optmenu.etoilesFixes',
    'Asteroids': 'optmenu.asteroids',
    'Midpoints': 'optmenu.midpoints',
    'Hybrid Hits': 'optmenu.hybridHits',
    'Dodecatemoria': 'optmenu.dodecatemoria',
    'Antiscia': 'optmenu.antiscia',
    'Contraantiscia': 'optmenu.contraantiscia',
    'Contra-antiscia': 'optmenu.contraantiscia2',
    'Arabic Parts': 'optmenu.arabicParts',
    'Arabic parts': 'optmenu.arabicParts2',
    'Parts Arabes': 'optmenu.partsArabes',
    'Fixstars to Nodes': 'optmenu.fixstarsToNodes',
    'Fixstars to intermediate HCs': 'optmenu.fixstarsToIntermediateHcs',
    'Fixstars to Fortuna': 'optmenu.fixstarsToFortuna',
    'Phasis mode': 'optmenu.phasisMode',
    'Astronomical': 'optmenu.astronomical',
    'Hellenistic': 'optmenu.hellenistic',
    'Swiss Ephemeris': 'optmenu.swissEphemeris',
    'Phasis modern planets': 'optmenu.phasisModernPlanets',
    'Cazimi mode': 'optmenu.cazimiMode',
    'Hellenistic · 1°': 'optmenu.hellenistic1',
    'Synodic Shift+Arrow': 'optmenu.synodicShiftarrow',
    'Station+Cazimi': 'optmenu.stationcazimi',
    'All': 'optmenu.all',
    'Eclipse overlay': 'optmenu.eclipseOverlay',
    'Lot of Fortune': 'optmenu.lotOfFortune',
    'Fortuna = Asc+(Moon-Sun)': 'optmenu.fortunaAscmoonsun',
    'Fortuna = Asc+(Sun-Moon) [Diurnal]': 'optmenu.fortunaAscsunmoonDiurnal',
    'Fortuna = Asc+(Moon-Sun) [Diurnal]': 'optmenu.fortunaAscmoonsunDiurnal',
    'Syzygy': 'optmenu.syzygy',
    'Moon': 'optmenu.moon',
    'Above Horizon': 'optmenu.aboveHorizon',
    'Above Horizon (Radix)': 'optmenu.aboveHorizonRadix',
    'Wheel layout': 'optmenu.wheelLayout',
    'Classic Wheel': 'optmenu.classicWheel',
    'Compact Wheel': 'optmenu.compactWheel',
    'Anglo Wheel': 'optmenu.angloWheel',
    'House line routing': 'optmenu.angloDenseLabelLayout',
    'Straight house lines': 'optmenu.leaderColumns',
    'Routed house lines': 'optmenu.routedCuspLines',
    'Broken lines, planets stay in sign': 'optmenu.signLockedCusps',
    'Sub charts as biwheels': 'optmenu.subChartsAsBiwheels',
    'Planetary hour': 'optmenu.planetaryHour',
    'Information': 'optmenu.information',
    'Seconds in header': 'optmenu.secondsInHeader',
    'Chart navigation bar': 'optmenu.chartNavigationBar',
    'Progressed angles': 'optmenu.progressedAngles',
    'True Solar Arc (Lon)': 'optmenu.trueSolarArcLon',
    'True Solar Arc (RA)': 'optmenu.trueSolarArcRa',
    'Naibod (RA)': 'optmenu.naibodRa',
    'Q2 / Mean Quotidian': 'optmenu.q2MeanQuotidian',
    'Progression day type': 'optmenu.progressionDayType',
    'Progressions / Transits': 'optmenu.progressionsTransits',
    'Chart': 'optmenu.chart',
    'Table': 'optmenu.table',
    'Both': 'optmenu.both',
    'Timed rows show radix': 'optmenu.timedRowsShowRadix',
    'Solar return year': 'optmenu.solarReturnYear',
    'Current year': 'optmenu.currentYear',
    'Next year': 'optmenu.nextYear',
    'Solar return location': 'optmenu.solarReturnLocation',
    'Use natal': 'optmenu.useNatal',
    'Ask': 'optmenu.ask',
    'Lunar return location': 'optmenu.lunarReturnLocation',
    'Planetary return location': 'optmenu.planetaryReturnLocation',
    'Marr sidereal solar returns': 'optmenu.marrSiderealSolarReturns',
    'Marr sidereal lunar returns': 'optmenu.marrSiderealLunarReturns',
    'Marr sidereal planetary returns': 'optmenu.marrSiderealPlanetaryReturns',
    'Whole-sign profections': 'optmenu.wholesignProfections',
    'Zodiacal profections': 'optmenu.zodiacalProfections',
    'Use zodiacal projections': 'optmenu.useZodiacalProjections',
    'Snap to solar return': 'optmenu.snapToSolarReturn',
    'Firdaria order': 'optmenu.firdariaOrder',
    'Step conjunction alerts': 'optmenu.stepConjunctionAlerts',
    'Lunar Mansions zodiac': 'optmenu.lunarMansionsZodiac',
    'Follow chart zodiac': 'optmenu.followChartZodiac',
    'Always sidereal': 'optmenu.alwaysSidereal',
    'Always tropical': 'optmenu.alwaysTropical',
    'Eclipse chart moment': 'optmenu.eclipseChartMoment',
    'Exact conjunction': 'optmenu.exactConjunction',
    'Eclipse maximum': 'optmenu.eclipseMaximum',
    'Relationship launcher': 'optmenu.relationshipLauncher',
    'Open Synastry first': 'optmenu.openSynastryFirst',
    'Open Composite first': 'optmenu.openCompositeFirst',
    'Local Space over ACG': 'optmenu.localSpaceOverAcg',
    'Traditional fixed-star names in PD lists': 'optmenu.traditionalFixedstarNamesInPdLists',
    'Derived Charts': 'optmenu.derivedCharts',
    'Simple Chart': 'optmenu.simpleChart',
    'Chart information': 'optmenu.chartInformation',
    'Parallel Transit': 'optmenu.parallelTransit',
    'Other Revolutions': 'optmenu.otherRevolutions',
    'Sidereal Return (Marr)': 'optmenu.siderealReturnMarr',
    'Tithi Pravesha (Annual Soli-Lunar Return)': 'chartmenu.tithiPravesha',
    'Lunar Phase (Embolismic)': 'chartmenu.lunarPhaseEmbolismic',
    'Jonas Arc': 'chartmenu.jonasArc',
    'Profections': 'optmenu.profections',
    'By sign': 'optmenu.bySign',
    'Continuous': 'optmenu.continuous',
    'Anchor to This Chart': 'optmenu.anchorToThisChart',
    'Find transits': 'optmenu.findTransits',
    'Primary directions': 'optmenu.primaryDirections',
    'For this point': 'optmenu.forThisPoint',
    'Surveil Studies...': 'optmenu.surveilStudies',
    'Clear Active Surveil Study': 'optmenu.clearActiveSurveilStudy',
    'Split into Radixes': 'optmenu.splitIntoRadixes',
    'Extract Participant': 'optmenu.extractParticipant',
    'Composite': 'optmenu.composite',
    'Untitled': 'optmenu.untitled',
    'Parallel Transit ': 'optmenu.parallelTransit2',
}
